# Docker Compose file for executing BATS tests

version: '2'
services:
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'futrli/buildkite-buildtools']
    volumes:
      - ".:/plugin"
