name: Buildkite Buildtools
description: Buildtools for manipulating Docker
author: https://github.com/futrli
requirements:
  - docker
configuration:
  properties:
    aws-account-id:
      type: string
    build-args:
      type: [ string, array ]
      minimum: 1
    context-path:
      type: string
    image-name:
      type: string
    tag:
      type: string
    task:
      type: string
    verbose:
      type: string
  required:
    - task
  dependencies:
    aws-account-id: [ task ]
    build-args: [ task ]
    context-path: [ task ]
    image-name: [ task ]
    tag: [ task ]
  additionalProperties: false
