name: Buildkite Buildtools
description: Buildtools for manipulating Docker
author: https://github.com/futrli
requirements:
  - docker
configuration:
  properties:
    aws-registry-id:
      type: string
    build-args:
      type: [ string, array ]
      minimum: 1
    context-path:
      type: string
    ecr-repository:
      type: string
    image-name:
      type: string
    tag:
      type: object
      properties:
        value:
          type: string
        script:
          type: string
    task:
      type: string
    verbose:
      type: string
  required:
    - task
  additionalProperties: false
  dependencies:
    aws-registry-id: [ task ]
    build-args: [ task ]
    context-path: [ task ]
    ecr-repository: [ task ]
    image-name: [ task ]
    tag: [ task ]
