#!/bin/bash

set -euo pipefail

# Path to this script
DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=../lib/shared.bash
. "$DIR/../lib/shared.bash"
# shellcheck source=../lib/aws.bash
. "$DIR/../lib/aws.bash"
# shellcheck source=../lib/docker.bash
. "$DIR/../lib/docker.bash"

echo "Add verbose argument to plugin to enable set -x and verbose mode"
verbose="$(plugin_read_list VERBOSE)"
export verbose
[[ -n ${verbose} ]] && set -x

tasks=()

# Work out what tasks to run
if [[ -n "$(plugin_read_list TASK)" ]]
then
    task="$(plugin_read_list TASK)"
    tasks+=("${task}")
fi

# Only allow a single task (for now)
if [[ ${#tasks[@]} -gt 1 ]] ; then
    echo "+++ Plugin error"
    echo "Only one command can be set"
    exit 1
fi

# Find the task that matches the task
if in_array "build" "${tasks[@]}" ; then
    # shellcheck source=../tasks/build.bash
    . "$DIR/../tasks/build.bash"
else
    echo "+++ Buildtools plugin error"
    echo "No build or run options were specified"
    exit 1
fi
